### ISSUE TITLE
component popper package

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/primitives#167]
packages/components/popper

Branch [popper](https://github.com/oku-ui/primitives/tree/popper)

[same radix](https://github.com/radix-ui/primitives/blob/main/packages/react/popper/src/Popper.tsx) popper package code

**Comment by productdevbook** [comment]
Brach [popper](https://github.com/oku-ui/primitives/tree/popper)

Radix Popover Styled: example https://601857eb614bae0021c9b9dd-jvztzayxuq.chromatic.com/?path=/story/components-popover--styled

Oku Popover Styled: http://localhost:6006/?path=/story/components-popper--styled


When you scroll and press the button there, the popper starts animation from the left corner, and there are some other visible bugs.


1. arrow is not on the box.
![image](https://github.com/oku-ui/primitives/assets/38668796/c749e04c-c854-4044-b235-a04a78c0433e)


2. Transition animation problem

https://github.com/oku-ui/primitives/blob/35a27c0f3beb06aae968cb8106cfb42d69ed4b73/packages/components/popper/src/stories/PopperDemo.vue#L37-L44

![image](https://github.com/oku-ui/primitives/assets/38668796/69bdea5e-fca2-4bfa-b5bb-ee6b37dde43f)

**Comment by dammy001** [comment]
@productdevbook I'll check it out tomorrow.
