### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/primitives#25]

**Comment by YeSuX** [comment]
I would like to claim this task. : )

**Comment by productdevbook** [comment]
@YeSuX you to

**Comment by faithfulojebiyi** [comment]
@YeSuX I have finished working on the toggle

**Comment by YeSuX** [comment]
> @YeSuX I have finished working on the toggle
> 
> 

But I have already claimed this task before and spent a lot of time on it. Please follow the component development process for the next time you develop a component...
