### ISSUE TITLE
Readme list of sponsors

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/primitives#30]
https://github.com/sponsors/productdevbook

How can we do as below, can someone make and pr for it? I think antfu had automated this. Thank you

Antfu: https://github.com/vitest-dev/vitest

![image](https://user-images.githubusercontent.com/38668796/234804422-90f63d7a-1ce3-44ad-bce5-ea753932f9b8.png)

**Comment by aussieboi** [comment]
he is using  tool he made. - https://github.com/antfu/sponsorkit

**Comment by innocenzi** [comment]
@productdevbook You should create a repository for this organization (eg `.github`), in which there is a recurring GitHub Action that generates these images using Anthony's `sponsorkit`. I can PR if you make the repository 👍

**Comment by productdevbook** [comment]
@innocenzi 

I was looking into it a bit, is this exactly ?

https://github.com/antfu/static/blob/master/.github/workflows/scheduler.yml

It would be great if you could, I would be very happy.


![image](https://user-images.githubusercontent.com/38668796/234840027-e48f045f-bd08-406f-ae4a-e65a4bb775cb.png)

It would be very good if you grouped like this.

**Comment by productdevbook** [comment]
https://github.com/antfu/static

okay iam craete new repo `static` and copy codes.

@jd-solanki thank you

**Comment by productdevbook** [comment]
https://github.com/oku-ui/static

forgot to share, sponsors are linked here.
