### ISSUE TITLE
(Presence) when change the display attribute of content, the animation can't work

### ISSUE THREAD

**Issue by YeSuX** [oku-ui/primitives#300]
### Describe the bug

https://github.com/oku-ui/primitives/assets/44074974/00f23ab2-1550-4299-ae1a-3a4cb8b40e0c

In stroybook，when I click Visibility button to change the display attribute, the content should have an animation when it appears or disappears, but it doesn't now.

### Reproduction

.

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 75.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    pnpm: 8.1.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/productdevbook/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by productdevbook** [comment]
I think I solved this problem, can you check again after pr merges. #346
