### ISSUE TITLE
toggle group tabindex dont change

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/primitives#304]
### Describe the bug

![image](https://github.com/oku-ui/primitives/assets/38668796/042cfd4a-0f7c-49f4-a668-264189a2a87f)

The tabindex numbers need to change when you click the buttons

### Reproduction

http://localhost:6006/?path=/story/components-togglegroup--styled

### System Info

```Shell
x
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/productdevbook/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Cr0zy07** [comment]
This issue I think is related to the roving-focus component #236, I will take a look at it.

**Comment by productdevbook** [comment]
working on the `radio-group` or `tabs` , but maybe he's there. If you solve it there, you can check `radio group` and `tabs` again.

**Comment by productdevbook** [comment]
roving-focus actually updates the index but not that attrs in the element. Interesting
