### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by Cr0zy07** [oku-ui/primitives#316]
Source: [menu](https://github.com/radix-ui/primitives/tree/eca6babd188df465f64f23f3584738b85dba610e/packages/react/menu)

Needs:

- [x] internal use-remove-scroll composable or [useScrollLock](https://vueuse.org/core/useScrollLock/) https://github.com/oku-ui/primitives/pull/314
- [x] [aria-hidden](https://www.npmjs.com/package/aria-hidden) https://github.com/oku-ui/primitives/pull/314

**Comment by Cr0zy07** [comment]
I will start doing this task...

**Comment by productdevbook** [comment]
Can you dm me if you use Discord or Twitter ?
