### ISSUE TITLE
more storybook and test add

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/primitives#358]
The following areas need to be checked and tested again. Missing areas need to be repaired

[Radix Storybook](https://601857eb614bae0021c9b9dd-jvztzayxuq.chromatic.com/?path=/story/components-toggle--chromatic)

[We Example Storybook](https://github.com/oku-ui/primitives/tree/main/packages/components/toast/src/stories) This is the best example and the old style of writing needs to be converted to this format.

Please post a comment if you would like to take part. and select components

3 step single pr may also be available.

## Step 1 - Components Storybook
[Example packages](https://github.com/oku-ui/primitives/tree/main/packages/core/popper)

 - [x] aspect-ratio @Cr0zy07
 - [x] avatar @Cr0zy07
 - [x] checkbox @Cr0zy07
 - [x] collapsible @Cr0zy07
 - [ ] dialog @Cr0zy07
 - [ ] hover-card
 - [x] label @Cr0zy07
 - [x] popover @productdevbook
 - [x] popper @productdevbook 
 - [ ] progress @mohi0
 - [x] radio-group @Cr0zy07
 - [x] separator @Cr0zy07
 - [ ] slider
 - [ ] switch
 - [ ] tabs
 - [x] toast @Cr0zy07
 - [x] toggle @Cr0zy07
 - [x] toggle-group @Cr0zy07
 - [x] toolbar
 - [x] tooltip @YeSuX 
 
 ## Step 2 - Components Test
 [Example packages](https://github.com/oku-ui/primitives/tree/main/packages/core/popper)
 [Vue Test Docs](https://test-utils.vuejs.org/)

 component is create `tests` folder and move test or create test. You can integrate some of the stories and add them to your tests.

 - [ ] aspect-ratio @Cr0zy07
 - [ ] avatar @Cr0zy07
 - [ ] checkbox @Cr0zy07
 - [ ] collapsible @Cr0zy07
 - [ ] dialog @Cr0zy07
 - [ ] hover-card
 - [ ] label @Cr0zy07
 - [ ] popover @productdevbook
 - [ ] popper @productdevbook 
 - [ ] progress @mohi0
 - [ ] radio-group @Cr0zy07
 - [ ] separator @Cr0zy07
 - [ ] slider
 - [ ] switch
 - [ ] tabs
 - [ ] toast @Cr0zy07
 - [ ] toggle @Cr0zy07
 - [ ] toggle-group @Cr0zy07
 - [ ] toolbar
 - [ ] tooltip @YeSuX 
 
 
## Step 3 Props and Types one file `props.ts` add 
[Example packages](https://github.com/oku-ui/primitives/tree/main/packages/core/popper)

 - [x] aspect-ratio @Cr0zy07
 - [x] avatar @Cr0zy07
 - [x] checkbox @Cr0zy07
 - [x] collapsible @Cr0zy07
 - [ ] dialog @Cr0zy07
 - [ ] hover-card
 - [x] label @Cr0zy07
 - [x] popover @productdevbook
 - [x] popper @productdevbook 
 - [ ] progress @mohi0
 - [x] radio-group @Cr0zy07
 - [x] separator @Cr0zy07
 - [ ] slider
 - [ ] switch
 - [ ] tabs
 - [ ] toast @Cr0zy07
 - [x] toggle @Cr0zy07
 - [x] toggle-group @Cr0zy07
 - [x] toolbar
 - [x] tooltip @YeSuX

**Comment by Cr0zy07** [comment]
I am willing to rewrite the first 5 components stories as a start! 

However, I have a suggestion, what if we remove `TailwindCSS` and `PostCSS` from the `devDeps` and just use plain `CSS`?

**Comment by Cr0zy07** [comment]
> > However, I have a suggestion, what if we remove `TailwindCSS` and `PostCSS` from the `devDeps` and just use plain `CSS`?
> 
> I'll take a look at this, create a new pr and import it.

What do you mean by "imposter it", which part are you referring to?. Also, should I make a PR for each component story or all together?

**Comment by productdevbook** [comment]
> Also, should I create a PR for each component story or all together?

@Cr0zy07 After sending the popper pr, you will see how it will work. Please Popper pr wait

**Comment by mturkoz93** [comment]
I can take the toolbar and the hover-card.

**Comment by productdevbook** [comment]
@Cr0zy07 The 3 structures for each component should be collected in 1 pr, each component should be pr separately.

Why should we do all 3 together in one pr?

We can see bugs while writing the stories, so we need to fix the code. Also, since the code will change, I think it is best to finish the tests in the same place.

I sent popper pr and merged them, I updated the texts here, please check.

**Comment by productdevbook** [comment]
@mturkoz93 added. Thank you :heart:

**Comment by mohi0** [comment]
I can contribute to progress bar

**Comment by productdevbook** [comment]
> I can contribute to progress bar

Thank you. I added.
