### ISSUE TITLE
Problem on installation card in oku docs

### ISSUE THREAD

**Issue by pulygarcia** [oku-ui/primitives#405]
### Describe the bug

black screen when click on "installation" card in oku documentation

### Reproduction

black screen when click on installation

### System Info

```Shell
black screen when click on installation
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/productdevbook/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by productdevbook** [comment]
Can you send  screenshot?

**Comment by pulygarcia** [comment]
Here are the screenshots. Before and after click on installation

![oku](https://github.com/oku-ui/primitives/assets/106268635/e97fdc0c-c35f-4f7a-9933-382d6403543b)
![oku-black](https://github.com/oku-ui/primitives/assets/106268635/d010e6f8-182e-44ef-be0f-124bb7e39329)

**Comment by productdevbook** [comment]
https://www.radix-ui.com/primitives/docs/overview/getting-started

This had to be written, that page is missing sorry :(

**Comment by productdevbook** [comment]
leave it open, we'll close it when you type it

**Comment by pulygarcia** [comment]
Its ok

**Comment by productdevbook** [comment]
new documentation is being written, so I'm closing this place.  Thank you ❤️  https://github.com/oku-ui/primitives/pull/560
