### ISSUE TITLE
TS to SFC

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/primitives#492]
We will try to convert all TS files to 100% SFC. If you want to help, you can see examples from the new TS to SFC prs I will send.

- [x] accordion @teleskop150750
- [x] alert-dialog @teleskop150750
- [x] arrow @teleskop150750
- [x] aspect-ratio @teleskop150750
- [x] avatar @teleskop150750
- [x] checkbox @teleskop150750
- [x] collapsible @teleskop150750
- [x] dialog @teleskop150750
- [x] direction @teleskop150750
- [x] dismissable-layer @teleskop150750
- [x] focus-guards @teleskop150750
- [x] focus-scope @teleskop150750
- [x] hover-card @teleskop150750
- [x] label @teleskop150750
- [x] menu @teleskop150750
- [x] popover @teleskop150750
- [x] popper @teleskop150750
- [x] portal @teleskop150750
- [x] presence @teleskop150750
- [x] primitive @teleskop150750
- [x] progress @teleskop150750
- [x] radio-group @teleskop150750
- [x] roving-focus @teleskop150750
- [x] scroll-area @teleskop150750
- [x] separator @teleskop150750
- [x] slider @teleskop150750
- [x] slot @teleskop150750
- [x] switch @teleskop150750
- [x] tabs @teleskop150750
- [x] toast @teleskop150750
- [x] toggle @teleskop150750
- [x] toggle-group @teleskop150750
- [x] toolbar @teleskop150750
- [x] tooltip @teleskop150750
- [x] visually-hidden @teleskop150750

**Comment by productdevbook** [comment]
tooltip (it won't shut off when you go outside. I put it together.) merged main. 

https://github.com/oku-ui/primitives/assets/38668796/130d78e5-b33b-4102-8644-e7a43aa6a190

**Comment by teleskop150750** [comment]
took ```scroll-area```

**Comment by teleskop150750** [comment]
took ```radio-group```

**Comment by teleskop150750** [comment]
took: ``` dialog```
