### ISSUE TITLE
dismissable-layer popover nested bug

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/primitives#494]
### Describe the bug

Radix: https://601857eb614bae0021c9b9dd-yloitnxbpo.chromatic.com/?path=/story/utilities-dismissablelayer--popover-nested

Oku: http://localhost:6006/?path=/story/utilities-dismissablelayer--popover-nested

[code](https://github.com/oku-ui/primitives/tree/main/packages/vue/src/dismissable-layer)

The video has a problem, the popover status is not displayed.

https://github.com/oku-ui/primitives/assets/38668796/f043c07f-d4ab-4914-8931-a674bb5c519b

### Reproduction

x

### System Info

```Shell
x
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/productdevbook/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by binaryfire** [comment]
Have you guys considered using Floating UI? Or do you prefer to avoid all dependencies?
