### ISSUE TITLE
add avatar test 

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/primitives#65]
We need to write a test for the avatar component.

- [ ] [create label.test.ts](https://github.com/oku-ui/primitives/tree/main/packages/components/avatar/src) in label src
- [ ] used vitest
- [ ] write the appropriate tests

**Comment by ramzzo** [comment]
If they didn't take the task, I would like to take it

**Comment by productdevbook** [comment]
Yes, thank you. the task is yours

**Comment by productdevbook** [comment]
do you continue ?
