### ISSUE TITLE
Ref attribute of Primitive component is not working, unable to use template references.

### ISSUE THREAD

**Issue by YeSuX** [oku-ui/primitives#79]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/44074974/236096238-a981d5bb-ea39-480c-8a47-9b43286aed8a.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/44074974/236096267-41415cb7-d32c-4bb2-a27c-15dd8ff0c3f9.png">

I don't know if it's related to #71, but it seems like the issue with Primitive refs hasn't been resolved.

**Comment by productdevbook** [comment]
that pr was for removing the ref error when i was writing component here and it fixed it. You can also access it with innerRef.

![image](https://user-images.githubusercontent.com/38668796/236104214-23f34e53-3a3d-4d29-a9ff-9bc033c0e923.png)
