### ISSUE TITLE
what is useComposedRefs ? 

### ISSUE THREAD

**Issue by productdevbook** [oku-ui/primitives#88]
I came across this thread with checkbox, I also wrote the npm library but I don't know if it's correct.

Also, I don't understand what exactly is the advantage of using the [oku-ui/checkbox](https://github.com/oku-ui/primitives/tree/main/packages/components/checkbox). Or how should we use it if we are going to use it?

- [x] [Radix ui checkbox](https://github.com/radix-ui/primitives/blob/main/packages/react/checkbox/src/Checkbox.tsx#L56)
- [x] [oku-ui/checkbox](https://github.com/oku-ui/primitives/blob/main/packages/components/checkbox/src/checkbox.ts#LL124C1-L127C1) check useComposedRefs
- [x] [oku-ui/compose-refs](https://github.com/oku-ui/primitives/tree/main/packages/core/compose-refs) core package check
- [x] explain the purpose of use, send correction pr

**Comment by YeSuX** [comment]
I think that useControllableState like v-bind, while useUncontrolledState like v-model.

You can refer to the source code of navie-ui that handles similar logic to useControllableState and useUncontrolledState.

source: https://github.com/tusen-ai/naive-ui/blob/main/src/checkbox/src/Checkbox.tsx#L175

demo: https://codesandbox.io/s/tender-grothendieck-yg5epy?file=/src/Demo.vue

**Comment by productdevbook** [comment]
this problem has been resolved. https://github.com/oku-ui/primitives/blob/main/packages/core/use-composable/src/useControllable.ts
